### ISSUE TITLE
Warning: Error Executing Section 3: Cannot find path

### ISSUE THREAD

**Issue by Atlowell** [MichiMunich/Windows10-Privacy#2]
Hello,

First off, thanks for making these scripts. I held off updating to Windows 10 for a long while partly because of the privacy concerns, and this helps ease that.

On a clean install of windows 10 (installed 2 days ago, only change made has been to relocate much of my user directory to another hard drive via a combination of changing the "location" property of folders and creating junctions), I am experiencing an issue.  When enabling privacy protection via the command in the README, I receive the following output:

```
    Hive: HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies


Name                           Property
----                           --------
DataCollection
WARNING: Error executing section 3: Cannot find path
'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\DeliveryOptimization\Config' because it does not exist.
```

and the script exits. Removing/commenting out the following lines related to update delivery optimization

```
#----------------------------------------------------------------------------------
	# disable update delivery optimization (also possible with GPO)
	$path = "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\DeliveryOptimization\Config"
	Set-ItemProperty -path $path -name DODownloadMode -value "0"
		
	# errorhandling
	if ($error.Count -gt 0)
	{
		errorhandling -code 3;
	}
```

causes the rest of the program to work correctly.

**Comment by MichiMunich** [comment]
Thanks also here for your message. Changed a few things in the script. Should work fine now.
