### ISSUE TITLE
Windows 10 Cleanup File Script Typo

### ISSUE THREAD

**Issue by Atlowell** [MichiMunich/Windows10-Privacy#3]
Based on the file names in the scripts directory, the command to run the Windows 10 cleanup script should be:

```
powershell.exe -NoProfile -ExecutionPolicy Bypass "& '.\Windows10_Cleanup.ps1'"
```

instead of 

```
powershell.exe -NoProfile -ExecutionPolicy Bypass "& '.\WindowsCleanup.ps1'"
```

**Comment by MichiMunich** [comment]
Thank you very much for your feedback. I have modified the scripts accordingly.
